### ISSUE TITLE
Starting softhddevice in detached mode leads to segfault of VDR (2.4.7)

### ISSUE THREAD

**Issue by hpannenb** [ua0lnj/vdr-plugin-softhddevice#39]
To better track the situation/issues with softhddevice in detached mode and several skins I create this issue.

Not having in depth knowledge it looks as if several skins (i.e. skinflatplus, skinnopacity etc.) try to create an OSD although there is not any available (in detached mode). 

Ref. also to https://vdr-portal.de

1. [[ansible] vdr 2.4.7 Segmentation Fault beim Start mit softhddevice und aktivem skinnopacity oder skinflat](https://www.vdr-portal.de/forum/index.php?thread/134546-ansible-vdr-2-4-7-segmentation-fault-beim-start-mit-softhddevice-und-aktivem-ski/)
2. [[0.7] Nach Start von Kodi stürzt VDR ab](https://www.vdr-portal.de/forum/index.php?thread/134538-0-7-nach-start-von-kodi-st%C3%BCrzt-vdr-ab/&postID=1341819#post1341819)

Regards,
Holger.

**Comment by MegaV0lt** [comment]
Not only intel based. NVidia has the same issue

**Comment by hpannenb** [comment]
Thanks @MegaV0lt : I changed the title accordingly.

Still I do not have any preference about where to fix this issue best: Either in the skins (each), in the section of softhddevices "detached" mode (i.e. return code?) or any other KISS solution available.

**Comment by ua0lnj** [comment]
Has it always been like this, or has it become after something?
Maybe it was after this commit:
https://github.com/ua0lnj/vdr-plugin-softhddevice/commit/4d5edf90d15232fae6ffca7943e6cc6848e79da3

In general, I still think that this is a skin problem.
Osd should not be displayed when the output is suspended.
Therefore, NULL when creating a pixmap tells the skin that the OSD is dummy. Why create a pixmap and allocate memory when output is disabled?
And the skindesigner works great with that.

upd: no, this is not because of the specified commit, it always seems that way. Softhdcuvid have this issue too for me.

**Comment by hpannenb** [comment]
Hi, @ua0lnj 

the last properly working softhddevice for me was a version 1.0.5 (1:1.0.5+git20200928-2-78f23fa-0yavdr0~bionic) under Ubuntu Bionic entirely based on yaVDR-ansible thus depending on seahawk1986's yaVDR PPAs (and building options).

Previous VDR version: 2.4.0 (on Bionic)
Current VDR version: 2.4.7 (on Focal)

I do not want to "blame" anyone and I appreciate the work You invest in this piece of code.

Regards,
Holger.

**Comment by ua0lnj** [comment]
Fixed https://github.com/ua0lnj/vdr-plugin-softhddevice/commit/7fff8f4ae0ec85f168d2b0bb203ced1bfe61ce44
No skin patches needed.
